# Generated by build_profile.py. Do not edit directly.
# ruff: noqa: Q000
# This file may contain private credentials.
# Regenerate after changing profile.json or credentials.json.

NAME_LINE1 = 'Profile'
NAME_LINE2 = 'Hub'
JOB_TITLE = 'Tufty 2350 Profile Badge'
PRIMARY_LABEL = 'github.com/KiloGramowy'
TAGLINE = 'QR // WDGWARS // WIGLE'
THEME = 'pcb'
BOARD_ICON = 'xiao_c5'

LINKS = [{'id': 'project',
  'title': 'PROJECT',
  'label': 'tufty-profile-hub',
  'url': 'https://github.com/KiloGramowy/tufty-profile-hub',
  'accent': 'cyan'}]
PAGE_ORDER = ['main', 'project', 'wdgwars', 'wigle']

WDGWARS_ENABLED = True
WDGWARS_API_KEY = ''
WDGWARS_REFRESH_MS = 21600000
WDGWARS_PAGE_ENTRY_COOLDOWN_MS = 60000

WIGLE_ENABLED = True
WIGLE_API_NAME = ''
WIGLE_API_TOKEN = ''
WIGLE_REFRESH_MS = 21600000
WIGLE_PAGE_ENTRY_COOLDOWN_MS = 60000

RETRY_MS = 60000
INPUT_DELAY_MS = 180

AUTO_BRIGHTNESS_ENABLED = True
AUTO_BRIGHTNESS_MIN = 0.22
AUTO_BRIGHTNESS_MAX = 1.0

PROFILE = {'name_line1': 'Profile',
 'name_line2': 'Hub',
 'job_title': 'Tufty 2350 Profile Badge',
 'primary_label': 'github.com/KiloGramowy',
 'tagline': 'QR // WDGWARS // WIGLE'}

PAGES = [{'id': 'main', 'type': 'main'},
 {'id': 'project', 'type': 'qr'},
 {'id': 'wdgwars', 'type': 'wdgwars'},
 {'id': 'wigle', 'type': 'wigle'}]

INTEGRATIONS = {'wdgwars': {'enabled': True,
             'auto_refresh_seconds': 21600,
             'page_entry_cooldown_seconds': 60,
             'wdgwars_api_key': ''},
 'wigle': {'enabled': True,
           'auto_refresh_seconds': 21600,
           'page_entry_cooldown_seconds': 60,
           'wigle_api_name': '',
           'wigle_api_token': ''}}
